import type { Product } from './types';

export const categories = ['Men', 'Women', 'Unisex', 'Sunglasses'];
export const frameStyles = ['Aviator', 'Wayfarer', 'Round', 'Cat Eye', 'Square'];

export const products: Product[] = [
  {
    id: 1,
    name: 'Classic Aviator',
    price: 150.00,
    description: 'Timeless aviator style with a modern twist. Perfect for any occasion.',
    image: 'https://picsum.photos/400/400?random=1',
    isFeatured: true,
    rating: 4.8,
    category: 'Sunglasses',
    frameStyle: 'Aviator',
  },
  {
    id: 2,
    name: 'Modern Wayfarer',
    price: 130.00,
    description: 'A contemporary take on the iconic wayfarer design.',
    image: 'https://picsum.photos/400/400?random=2',
    isFeatured: true,
    rating: 4.7,
    category: 'Men',
    frameStyle: 'Wayfarer',
  },
  {
    id: 3,
    name: 'Round Intellectual',
    price: 165.00,
    description: 'Smart and sophisticated round frames for a vintage look.',
    image: 'https://picsum.photos/400/400?random=3',
    isFeatured: true,
    rating: 4.9,
    category: 'Unisex',
    frameStyle: 'Round',
  },
  {
    id: 4,
    name: 'Chic Cat Eye',
    price: 175.00,
    description: 'Elegant cat eye frames that make a bold statement.',
    image: 'https://picsum.photos/400/400?random=4',
    isFeatured: true,
    rating: 4.6,
    category: 'Women',
    frameStyle: 'Cat Eye',
  },
  {
    id: 5,
    name: 'Bold Square',
    price: 140.00,
    description: 'Confident and stylish square frames for a sharp look.',
    image: 'https://picsum.photos/400/400?random=5',
    isFeatured: false,
    rating: 4.5,
    category: 'Men',
    frameStyle: 'Square',
  },
  {
    id: 6,
    name: 'Minimalist Round',
    price: 155.00,
    description: 'Sleek and minimalist round frames for everyday wear.',
    image: 'https://picsum.photos/400/400?random=6',
    isFeatured: false,
    rating: 4.8,
    category: 'Unisex',
    frameStyle: 'Round',
  },
  {
    id: 7,
    name: 'Glamour Sunglasses',
    price: 190.00,
    description: 'Oversized and glamorous sunglasses for the ultimate diva look.',
    image: 'https://picsum.photos/400/400?random=7',
    isFeatured: false,
    rating: 4.9,
    category: 'Sunglasses',
    frameStyle: 'Square',
  },
  {
    id: 8,
    name: 'Vintage Wayfarer',
    price: 135.00,
    description: 'Authentic vintage-inspired wayfarer frames.',
    image: 'https://picsum.photos/400/400?random=8',
    isFeatured: false,
    rating: 4.6,
    category: 'Women',
    frameStyle: 'Wayfarer',
  },
];
